[package]
name = "liq-sim"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
liq-types = { path = "../liq-types" }
alloy-primitives = { workspace = true, features = ["std"] }
alloy-sol-types = { workspace = true, features = ["std"] }
revm = { workspace = true }
rtrb = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
alloy-primitives = { workspace = true, features = ["std"] }

[lints]
workspace = true
