#!/usr/bin/env python3
"""
WP C3 — regenerate D15 prune filter from committed registry/registry.json.

Merges Essential extraction (registry) + completion pass (on-chain oracle/DEX/flash tiers).
Outputs: tools/d15/d15_addresses.complete.json, ops/reth/reth.toml, completeness_report.md

Usage:
  python tools/d15/regenerate.py --registry registry/registry.json
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import time
from collections import Counter, defaultdict
from pathlib import Path

from web3 import Web3

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "tools"))

from d15.checklist import evaluate  # noqa: E402
from d15.complete import Completer, run_completion  # noqa: E402
from d15.essential import essential_from_registry, load_registry  # noqa: E402
from d15.roots import KNOWN_BEFORE  # noqa: E402


def _before_for_entry(e: dict) -> int:
    bb = e.get("before_block")
    if bb is not None and int(bb) > 0:
        return int(bb)
    return KNOWN_BEFORE.get(e["address"].lower(), 0)


def write_reth_toml(path: Path, merged: list[dict]) -> None:
    lines = [
        "# Generated by tools/d15/regenerate.py — do not hand-edit; re-run from registry.",
        "# GUIDE 16 §0b prune profile. Human sign-off at H1 before sync.",
        "",
        "[prune]",
        "block_interval = 5",
        "",
        "[prune.segments]",
        'sender_recovery = "full"',
        "account_history = { distance = 10_064 }",
        "storage_history = { distance = 10_064 }",
        "",
        "[prune.segments.receipts_log_filter]",
    ]
    for e in sorted(merged, key=lambda x: (x["protocol"], x["kind"], x["address"].lower())):
        bb = _before_for_entry(e)
        lines.append(
            f'"{e["address"].lower()}" = {{ before = {bb} }}  # {e["protocol"]} {e["kind"]} — {e["source"][:70]}'
        )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _classify_legacy_only(addr: str, old_entries: list[dict]) -> str:
    by_addr = {e["address"].lower(): e for e in old_entries}
    e = by_addr.get(addr)
    if not e:
        return "other"
    p, k = e.get("protocol"), e.get("kind")
    if p == "silo-v2" and k in ("share_collateral", "share_debt", "share_protected"):
        return "silo_share_tokens"
    if p == "fluid" and k == "vault":
        return "fluid_vaults"
    if p == "gearbox-v3":
        return "gearbox"
    if p == "liquity-v2" and k in ("troveManager", "stabilityPool", "activePool", "borrowerOperations", "sortedTroves", "troveNFT"):
        return "liquity_branch"
    if p in ("uniswap-v3", "curve", "kyber-elastic") and k == "pool":
        return "dex_pools_completion"
    if p == "asset" and k == "erc20":
        return "completion_assets"
    if k in ("factory", "meta_registry", "contracts_register", "erc20_pool_factory", "erc721_pool_factory", "vault_factory"):
        return "factories_registries"
    if p == "chainlink" and "phase" in k:
        return "chainlink_phase_aggregators"
    return "other"


def diff_legacy(out_dir: Path, merged: list[dict]) -> str:
    guides = ROOT / "liquidator-guides"
    legacy_json = guides / "d15_addresses.complete.json"
    lines = ["## Diff vs liquidator-guides/d15_addresses.complete.json (2026-09-19 pass)", ""]
    new_set = {e["address"].lower() for e in merged}
    if not legacy_json.is_file():
        lines.append("- Legacy JSON not found — skip diff.")
        return "\n".join(lines) + "\n"

    old = json.loads(legacy_json.read_text(encoding="utf-8"))
    old_entries = old.get("addresses", [])
    old_set = {e["address"].lower() for e in old_entries}
    only_new = sorted(new_set - old_set)
    only_old = sorted(old_set - new_set)
    lines.append(f"- Legacy JSON addresses: **{len(old_set)}**; this run: **{len(new_set)}**")
    lines.append(f"- Only in this run (registry C2): **{len(only_new)}**")
    lines.append(f"- Only in legacy complete (dropped): **{len(only_old)}**")
    if only_new[:5]:
        lines.append(f"- Sample new-only: {', '.join(only_new[:5])}")
    if only_old[:5]:
        lines.append(f"- Sample legacy-only: {', '.join(only_old[:5])}")

    buckets: Counter[str] = Counter()
    for a in only_old:
        buckets[_classify_legacy_only(a, old_entries)] += 1
    lines.append("")
    lines.append("### Dropped address breakdown (legacy-only)")
    lines.append("")
    lines.append("| Category | Count |")
    lines.append("|---|---:|")
    for label, title in (
        ("silo_share_tokens", "Silo V2 share tokens"),
        ("fluid_vaults", "Fluid vault contracts"),
        ("gearbox", "Gearbox credit managers / pools / oracles"),
        ("liquity_branch", "Liquity V2 branch contracts (ex price feeds)"),
        ("dex_pools_completion", "DEX pools from completion dex-pools pass"),
        ("completion_assets", "ERC-20 assets from completion asset pass"),
        ("factories_registries", "Factories / registries"),
        ("chainlink_phase_aggregators", "Chainlink phase aggregators"),
        ("other", "Other / unclassified"),
    ):
        if buckets[label]:
            lines.append(f"| {title} | {buckets[label]} |")
    lines.append(f"| **Total dropped** | **{len(only_old)}** |")
    lines.append("")
    lines.append(
        "Expected net deltas: C2 registry adds compound-v2 forks, 57 Aave V4 spokes, "
        "996 registry univ3 pools, admitted-market tokens; completion re-adds fluid/gearbox/liquity "
        "branch coverage via on-chain roots."
    )
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--registry", default=str(ROOT / "registry" / "registry.json"))
    ap.add_argument("--rpc", default="https://ethereum.publicnode.com")
    ap.add_argument("--logs-rpc", default="https://gateway.tenderly.co/public/mainnet")
    ap.add_argument("--out-dir", default=str(ROOT / "tools" / "d15"))
    ap.add_argument("--skip-dex", action="store_true")
    args = ap.parse_args()

    out_dir = Path(args.out_dir)
    reg = load_registry(Path(args.registry))
    base_entries = essential_from_registry(reg)
    print(f"Essential from registry: {len(base_entries)} addresses")

    w3 = Web3(Web3.HTTPProvider(args.rpc, request_kwargs={"timeout": 60}))
    w3_logs = Web3(Web3.HTTPProvider(args.logs_rpc, request_kwargs={"timeout": 60}))
    head = w3.eth.block_number
    print(f"head {head}")

    c = Completer(w3, w3_logs)
    for e in base_entries:
        c.seen.add(e["address"].lower())
        if e.get("kind") == "erc20":
            c.add_asset(e["address"], e.get("source", "asset"))

    t0 = time.time()
    run_completion(c, base_entries, args.skip_dex)

    new = c.entries
    merged = base_entries + new
    failures = dict(c.failures)
    counts = Counter((e["protocol"], e["kind"]) for e in merged)

    payload = {
        "generated_at": time.strftime("%Y-%m-%dT%H:%M:%S%z"),
        "chain_id": 1,
        "registry_block": reg.get("generated_at_block"),
        "rpc": args.rpc,
        "logs_rpc": args.logs_rpc,
        "head_block": head,
        "tier": "registry Essential + completion (D15 15-class)",
        "base_count": len(base_entries),
        "added_count": len(new),
        "counts_by_class": {f"{p}/{k}": v for (p, k), v in sorted(counts.items())},
        "failures": failures,
        "notes": c.notes,
        "addresses": merged,
    }

    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "d15_addresses.complete.json").write_text(json.dumps(payload, indent=1) + "\n", encoding="utf-8")

    write_reth_toml(ROOT / "ops" / "reth" / "reth.toml", merged)

    checklist_rows = evaluate(merged, failures)
    cl_md = [
        "# D15 completeness report (15-class checklist)",
        "",
        f"Total addresses: **{len(merged)}**",
        "",
        "| Class | Check | Pass | Detail |",
        "|---:|---|:---:|---|",
    ]
    for r in checklist_rows:
        cl_md.append(f"| {r['class']} | {r['name']} | {'PASS' if r['pass'] else 'FAIL'} | {r['detail']} |")
    cl_md.append("")
    cl_md.append("## Per-class counts (merged)")
    cl_md.append("")
    cl_md.append("| protocol | kind | n |")
    cl_md.append("|---|---|---:|")
    for (p, k), v in sorted(counts.items()):
        cl_md.append(f"| {p} | {k} | {v} |")
    cl_md.append(f"| **total** | | **{len(merged)}** |")
    cl_md.append("")
    cl_md.append("## Failures")
    cl_md.extend([f"- `{k}`: {v}" for k, v in failures.items()] or ["- (none)"])
    cl_md.append("")
    cl_md.append(diff_legacy(out_dir, merged))
    cl_md.append(f"\nWall time {time.time() - t0:.0f}s.")
    (out_dir / "completeness_report.md").write_text("\n".join(cl_md) + "\n", encoding="utf-8")

    print(f"done: essential {len(base_entries)} + {len(new)} = {len(merged)} in {time.time() - t0:.0f}s")
    print(f"wrote {out_dir}/d15_addresses.complete.json and ops/reth/reth.toml; failures={len(failures)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
