#!/usr/bin/env python3
"""
WP C3 — regenerate D15 prune filter from committed registry/registry.json.

Merges Essential extraction (registry) + completion pass (on-chain oracle/DEX/flash tiers).
Outputs: tools/d15/*, ops/reth/reth.toml

Usage:
  python tools/d15/regenerate.py --registry registry/registry.json
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import time
from collections import Counter, defaultdict
from pathlib import Path

from web3 import Web3

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "tools"))

from d15.checklist import evaluate  # noqa: E402
from d15.complete import Completer  # noqa: E402
from d15.essential import essential_from_registry, load_registry  # noqa: E402
from d15.roots import KNOWN_BEFORE, ROOTS  # noqa: E402


def _before_for_entry(e: dict) -> int:
    bb = e.get("before_block")
    if bb is not None and int(bb) > 0:
        return int(bb)
    return KNOWN_BEFORE.get(e["address"].lower(), 0)


def run_completion(c: Completer, base_entries: list[dict], skip_dex: bool) -> None:
    by = defaultdict(list)
    for e in base_entries:
        by[(e["protocol"], e["kind"])].append(e["address"])

    def step(name, fn, *a):
        t = time.time()
        try:
            fn(*a)
        except Exception as ex:  # noqa: BLE001
            c.failures[f"step:{name}"] = str(ex)[:300]
            print(f"[{name}] FAILED {ex}")
        print(f"[{name}] +{len(c.entries)} new, {time.time() - t:.0f}s", flush=True)

    step("constants", c.constants)
    step("aave-v3/spark oracles", c.aave_v3_like, base_entries)
    step("aave-v4 oracles", c.aave_v4, base_entries, 24_500_000)
    if by[("compound-v3", "configurator")]:
        step("compound-v3", c.compound_v3, by[("compound-v3", "configurator")][0], 15_331_586)
    else:
        step("compound-v3", c.compound_v3, ROOTS["compound_v3_configurator"], 15_331_586)
    step("morpho", c.morpho, ROOTS["morpho_blue"], 18_883_124)
    step("euler", c.euler, by[("euler-v2", "vault")])
    step("liquity", c.liquity, [a for a in by[("liquity-v2", "priceFeed")] if a])
    step(
        "sky",
        c.sky,
        by[("sky-maker", "ilk_registry")][0] if by[("sky-maker", "ilk_registry")] else ROOTS["ilk_registry"],
        "0x135954d155898D42C90D2a57824C690e0c7BEf1B",
        "0x65C79fcB50Ca1594B025960e539eD7A9a6D434A3",
    )
    step("gearbox", c.gearbox, by[("gearbox-v3", "credit_manager")])
    silos_by_cfg: dict[str, list[str]] = defaultdict(list)
    for e in base_entries:
        if e["protocol"] == "silo-v2" and e["kind"] == "silo":
            m = re.search(r"(0x[0-9a-fA-F]{40})", e.get("source", ""))
            if m:
                silos_by_cfg[m.group(1).lower()].append(e["address"])
    step("silo", c.silo, by[("silo-v2", "silo_config")], silos_by_cfg)
    step("fluid", c.fluid, by[("fluid", "vault")])
    step("feed-registry", c.feed_registry, "0x47Fb2585D2C56Fe188D0E6ec628a38b74fCeeeDf")
    if not skip_dex:
        step(
            "dex-pools",
            c.dex_pools,
            "0x1F98431c8aD98523631AE4a59f267346ea31F984",
            "0xF98B45FA17DE75FB1aD0e7aFD971b0ca00e379fC",
            "0x5F1dddbf348aC2fbe22a163e30F99F9ECE3DD50a",
        )
    c.assets_as_entries()


def write_reth_toml(path: Path, merged: list[dict]) -> None:
    lines = [
        "# Generated by tools/d15/regenerate.py — do not hand-edit; re-run from registry.",
        "# GUIDE 16 §0b prune profile. Human sign-off at H1 before sync.",
        "",
        "[prune]",
        "block_interval = 5",
        "",
        "[prune.segments]",
        'sender_recovery = "full"',
        "account_history = { distance = 10_064 }",
        "storage_history = { distance = 10_064 }",
        "",
        "[prune.segments.receipts_log_filter]",
    ]
    for e in sorted(merged, key=lambda x: (x["protocol"], x["kind"], x["address"].lower())):
        bb = _before_for_entry(e)
        lines.append(
            f'"{e["address"].lower()}" = {{ before = {bb} }}  # {e["protocol"]} {e["kind"]} — {e["source"][:70]}'
        )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def diff_legacy(out_dir: Path, merged: list[dict]) -> str:
    guides = ROOT / "liquidator-guides"
    legacy_json = guides / "d15_addresses.complete.json"
    legacy_toml = guides / "d15_receipts_log_filter.complete.toml"
    lines = ["## Diff vs liquidator-guides/*.complete.* (2026-09-19 pass)", ""]
    new_set = {e["address"].lower() for e in merged}
    if legacy_json.is_file():
        old = json.loads(legacy_json.read_text(encoding="utf-8"))
        old_set = {e["address"].lower() for e in old.get("addresses", [])}
        only_new = sorted(new_set - old_set)
        only_old = sorted(old_set - new_set)
        lines.append(f"- Legacy JSON addresses: **{len(old_set)}**; this run: **{len(new_set)}**")
        lines.append(f"- Only in this run (registry C2): **{len(only_new)}**")
        lines.append(f"- Only in legacy complete (dropped): **{len(only_old)}**")
        if only_new[:5]:
            lines.append(f"- Sample new-only: {', '.join(only_new[:5])}")
        if only_old[:5]:
            lines.append(f"- Sample legacy-only: {', '.join(only_old[:5])}")
        lines.append(
            "- Expected deltas: C2 registry adds compound-v2 forks, 57 Aave V4 spokes, "
            "996 registry univ3 pools, admitted-market tokens; legacy Essential omitted "
            "fluid/gearbox/compound-v3 if re-discovered only via completion roots."
        )
    else:
        lines.append("- Legacy `d15_addresses.complete.json` not found — skip diff.")
    if legacy_toml.is_file():
        old_addrs = set()
        for line in legacy_toml.read_text(encoding="utf-8").splitlines():
            m = re.match(r'"((0x)[0-9a-f]+)"\s*=', line.strip())
            if m:
                old_addrs.add(m.group(1).lower())
        lines.append(f"- Legacy TOML filter lines: **{len(old_addrs)}** vs **{len(new_set)}** now.")
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--registry", default=str(ROOT / "registry" / "registry.json"))
    ap.add_argument("--rpc", default="https://ethereum.publicnode.com")
    ap.add_argument("--logs-rpc", default="https://gateway.tenderly.co/public/mainnet")
    ap.add_argument("--out-dir", default=str(ROOT / "tools" / "d15"))
    ap.add_argument("--skip-dex", action="store_true")
    args = ap.parse_args()

    out_dir = Path(args.out_dir)
    reg = load_registry(Path(args.registry))
    base_entries = essential_from_registry(reg)
    print(f"Essential from registry: {len(base_entries)} addresses")

    w3 = Web3(Web3.HTTPProvider(args.rpc, request_kwargs={"timeout": 60}))
    w3_logs = Web3(Web3.HTTPProvider(args.logs_rpc, request_kwargs={"timeout": 60}))
    head = w3.eth.block_number
    print(f"head {head}")

    c = Completer(w3, w3_logs)
    for e in base_entries:
        c.seen.add(e["address"].lower())
        if e.get("kind") == "erc20":
            c.add_asset(e["address"], e.get("source", "asset"))

    t0 = time.time()
    run_completion(c, base_entries, args.skip_dex)

    new = c.entries
    merged = base_entries + new
    failures = dict(c.failures)
    counts = Counter((e["protocol"], e["kind"]) for e in merged)

    payload = {
        "generated_at": time.strftime("%Y-%m-%dT%H:%M:%S%z"),
        "chain_id": 1,
        "registry_block": reg.get("generated_at_block"),
        "rpc": args.rpc,
        "logs_rpc": args.logs_rpc,
        "head_block": head,
        "tier": "registry Essential + completion (D15 15-class)",
        "base_count": len(base_entries),
        "added_count": len(new),
        "counts_by_class": {f"{p}/{k}": v for (p, k), v in sorted(counts.items())},
        "failures": failures,
        "notes": c.notes,
        "addresses": merged,
    }

    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "d15_addresses.json").write_text(
        json.dumps({**payload, "addresses": base_entries, "added_count": 0}, indent=1) + "\n",
        encoding="utf-8",
    )
    (out_dir / "d15_addresses.complete.json").write_text(json.dumps(payload, indent=1) + "\n", encoding="utf-8")

    filter_lines = [
        "# receipts_log_filter — tools/d15/regenerate.py",
        "",
        "[prune.segments.receipts_log_filter]",
    ]
    for e in sorted(merged, key=lambda x: (x["protocol"], x["kind"], x["address"].lower())):
        bb = _before_for_entry(e)
        filter_lines.append(
            f'"{e["address"].lower()}" = {{ before = {bb} }}  # {e["protocol"]} {e["kind"]} — {e["source"][:70]}'
        )
    (out_dir / "d15_receipts_log_filter.complete.toml").write_text("\n".join(filter_lines) + "\n", encoding="utf-8")

    write_reth_toml(ROOT / "ops" / "reth" / "reth.toml", merged)

    checklist_rows = evaluate(merged, failures)
    cl_md = ["# D15 completeness report (15-class checklist)", "", f"Total addresses: **{len(merged)}**", "", "| Class | Check | Pass | Detail |", "|---:|---|:---:|---|"]
    for r in checklist_rows:
        cl_md.append(f"| {r['class']} | {r['name']} | {'PASS' if r['pass'] else 'FAIL'} | {r['detail']} |")
    cl_md.append("")
    cl_md.append("## Failures")
    cl_md.extend([f"- `{k}`: {v}" for k, v in failures.items()] or ["- (none)"])
    cl_md.append("")
    cl_md.append(diff_legacy(out_dir, merged))
    cl_md.append(f"\nWall time {time.time() - t0:.0f}s.")
    (out_dir / "completeness_report.md").write_text("\n".join(cl_md) + "\n", encoding="utf-8")

    print(f"done: essential {len(base_entries)} + {len(new)} = {len(merged)} in {time.time() - t0:.0f}s")
    print(f"wrote {out_dir} and ops/reth/reth.toml; failures={len(failures)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
