#!/usr/bin/env python3
"""Generate config/protocols/morpho-blue.toml from the chain and the registry.

Every `morpho-blue` registry entry is one market id. At one pinned block the
market's params are re-read from the singleton (`idToMarketParams(id)`), not
taken from the registry copy. A market is pinned when its loan and
collateral tokens are both interned and its oracle is non-zero:

  assets        = every interned token some pinned market lends or takes as
                  collateral (intern id + decimals)
  price_sources = one `(oracle, collateral, loan)` pin per distinct triple
                  (T16: a Morpho oracle is only safe for the pair it was
                  deployed for)

Market ids: the adapter assigns its own from `CreateMarket` logs, starting at
`first_market`. Allocation (see docs/coverage): 0..=3480 registry intern,
3508..=3510 Liquity, 3511..=3999 Euler, 4000..=4199 Fluid, 4200..=4299
Gearbox — Morpho takes catalog 5000, markets from 5001.

`feed` is informational (nothing joins on `MarketRow.price_feed`; Morpho
health prices through each market's own oracle): FeedId 0, as Gearbox does.

Usage: MAINNET_RPC_URL=... python tools/registry/gen_morpho_toml.py [--dry-run]
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

from eth_abi import decode, encode

sys.path.insert(0, str(Path(__file__).parent))
from discover_exits import Chain, sel  # noqa: E402
from gen_aave_v3_toml import intern_ids  # noqa: E402

REG = Path("registry/registry.json")
OUT = Path("config/protocols/morpho-blue.toml")
MORPHO = "0xbbbbbbbbbb9cc5e90e3b3af64bdaf62c37eeffcb"
ZERO = "0x0000000000000000000000000000000000000000"
CATALOG = 5000
FIRST_MARKET = 5001


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()
    chain = Chain(os.environ["MAINNET_RPC_URL"])
    reg = json.loads(REG.read_text(encoding="utf-8"))
    tokens, protocols, _markets, _feeds = intern_ids(reg)
    ids = sorted(p["market"].lower() for p in reg["protocols"].values()
                 if p["family"] == "morpho-blue")
    res = chain.multicall([(MORPHO, sel("idToMarketParams(bytes32)")
                            + encode(["bytes32"], [bytes.fromhex(i[2:])])) for i in ids])
    assets: dict[str, int] = {}
    pins: set[tuple[str, int, int]] = set()
    skipped = {"read": 0, "idle": 0, "unmapped": 0, "registry_mismatch": 0}
    by_id = {p["market"].lower(): p for p in reg["protocols"].values() if p["family"] == "morpho-blue"}
    for mid, (ok, raw) in zip(ids, res):
        if not ok or len(raw) < 160:
            skipped["read"] += 1
            continue
        loan, coll, oracle, _irm, _lltv = decode(["address", "address", "address", "address", "uint256"], raw)
        loan, coll, oracle = loan.lower(), coll.lower(), oracle.lower()
        r = by_id[mid]
        if (r.get("loan_token", "").lower(), r.get("collateral_token", "").lower(),
                r.get("oracle", "").lower()) != (loan, coll, oracle):
            skipped["registry_mismatch"] += 1
        if oracle == ZERO or coll == ZERO:
            skipped["idle"] += 1
            continue
        if loan not in tokens or coll not in tokens:
            skipped["unmapped"] += 1
            continue
        assets[loan] = tokens[loan]
        assets[coll] = tokens[coll]
        pins.add((oracle, tokens[coll], tokens[loan]))

    decimals = {a: reg["tokens"][a]["decimals"] for a in assets}
    lines = [
        "# Morpho Blue mainnet (family `morpho-blue` in registry/registry.json).",
        "# Generated by tools/registry/gen_morpho_toml.py — do not hand-edit.",
        f"# Market params re-read from the singleton at block {chain.block}.",
        f"# {len(ids)} registry markets -> {len(pins)} (oracle, collateral, loan) pins over",
        f"# {len(assets)} assets. Not pinned: {skipped['idle']} idle (no oracle/collateral),",
        f"# {skipped['unmapped']} with a token outside the registry, {skipped['read']} unreadable.",
        f"# Registry copy disagreed with the chain on {skipped['registry_mismatch']} market(s); chain wins.",
        "# MarketIds: catalog 5000, markets from 5001 (after Gearbox 4200..=4299).",
        "# feed = 0 is informational only (Morpho prices through each market oracle).",
        "",
        f"protocol = {protocols['morpho-blue']}",
        f"pinned_through = {chain.block}",
        f'morpho = "{MORPHO}"',
        f"catalog = {CATALOG}",
        f"first_market = {FIRST_MARKET}",
        "",
    ]
    for addr, aid in sorted(assets.items(), key=lambda kv: kv[1]):
        lines += ["[[assets]]", f'underlying = "{addr}"', f"asset = {aid}", "feed = 0",
                  f"decimals = {decimals[addr]}", ""]
    for oracle, c, l in sorted(pins, key=lambda p: (p[1], p[2], p[0])):
        lines += ["[[price_sources]]", f'oracle = "{oracle}"', f"collateral = {c}", f"loan = {l}", ""]
    print(f"{len(ids)} markets, {len(pins)} pins, {len(assets)} assets, skipped {skipped}")
    if args.dry_run:
        return 0
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
