"""Triage the registry tokens that have no exit (coverage plan 1D, step 3).

    python tools/registry/triage_exits.py

Offline: reads `registry/registry.json`, `config/protocols/*.toml` and, when
present, the three-month scan (`crates/liq-replay/tests/historical/
liquidations-scan.json`). Writes `docs/coverage/exit-triage.md`.

A token has an exit when a registry pool holds it or it has an unwrap the
bot's loader takes (as `scan_liquidations.py` judges it). For each token
without one:

    collateral   the scan saw it seized, or a bound market lists it as
                 collateral (Morpho `collateral_token`; Euler collateral
                 vault shares; Silo sides; Compound underlyings)
    kind         what it is, from the registry entry: Euler share, Pendle PT,
                 Pendle LP, Curve LP (not NG), Curve gauge, other
    next step    what would give it an exit, by kind

The ranking is the scan's: liquidations whose collateral had no exit, by
repaid USD. Tokens no liquidation seized are counted, not listed.
"""

import json
import os
import re
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SCAN = ROOT / "crates/liq-replay/tests/historical/liquidations-scan.json"
OUT = ROOT / "docs/coverage/exit-triage.md"
WETH = "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2"

NEXT = {
    "euler share": "ERC-4626 unwrap is refused (redeem hooked) or unwraps into an asset with no pool: route the asset",
    "pendle PT": "`discover_unwraps.py --kinds pendle_pt` (matured: redeem through the YT; live: sell on its market)",
    "pendle LP": "a Pendle LP unwrap kind (Executor venue + router kind)",
    "curve LP (not NG)": "a non-NG Curve LP unwrap (separate LP token, int128 or uint256 index; 1D step 4)",
    "curve gauge": "a gauge-withdraw unwrap into its LP, then the LP's exit",
    "other": "find a pool (`discover_exits.py`, Balancer / Fluid DEX if only there) or an unwrap",
}


def kind_of(t: dict, euler_shares: set, addr: str) -> str:
    s = (t.get("symbol") or "").lower()
    n = (t.get("name") or "").lower()
    if addr in euler_shares:
        return "euler share"
    if s.startswith("pt-") or "principal token" in n:
        return "pendle PT"
    if s.startswith("lp-") or "pendle market" in n or "pendle lp" in n:
        return "pendle LP"
    if "gauge" in n or s.endswith("-gauge"):
        return "curve gauge"
    if "crv" in s or "curve" in n:
        return "curve LP (not NG)"
    return "other"


def main() -> None:
    reg = json.loads((ROOT / "registry/registry.json").read_text(encoding="utf-8"))
    toks = {k.lower(): v for k, v in reg["tokens"].items()}
    has_pool = set()
    for p in reg["pools"].values():
        for t in [p.get("token0"), p.get("token1")] + p.get("coins", []):
            if t:
                has_pool.add(t.lower())
    no_exit = {a for a, t in toks.items() if a != WETH and a not in has_pool and not t.get("unwrap")}

    cfg = {f: (ROOT / "config/protocols" / f).read_text(encoding="utf-8").lower()
           for f in os.listdir(ROOT / "config/protocols") if f.endswith(".toml")}
    # Euler: an interned share's `underlying` is its own address.
    euler_shares = set(re.findall(r'underlying = "(0x[0-9a-f]{40})"', cfg.get("euler-v2.toml", "")))
    euler_shares &= set(re.findall(r'"(0x[0-9a-f]{40})"', cfg.get("euler-v2.toml", "").split("[[assets]]")[0]))
    collateral = set(euler_shares)
    for v in reg["protocols"].values():
        if v.get("collateral_token"):
            collateral.add(v["collateral_token"].lower())
    for f in ("silo-v2.toml", "compound-v2.toml", "aave-v3.toml", "aave-v2.toml", "spark.toml"):
        collateral |= set(re.findall(r'(?:token|underlying) = "(0x[0-9a-f]{40})"', cfg.get(f, "")))

    seized = defaultdict(lambda: [0, 0.0])
    scan_note = "no scan file"
    if SCAN.exists():
        sc = json.loads(SCAN.read_text(encoding="utf-8"))
        evs = sc.get("liquidations", [])
        scan_note = f"blocks {sc.get('from')}..{sc.get('to')}, {len(evs)} liquidations"
        for e in evs:
            c = (e.get("collateral") or "").lower()
            if e.get("blocked_by") == "no-exit" and c:
                seized[c][0] += 1
                seized[c][1] += e.get("repaid_usd") or 0.0

    rows = Counter()
    for a in no_exit:
        k = kind_of(toks[a], euler_shares, a)
        rows[(k, a in collateral or a in seized)] += 1

    L = ["# Exit triage", "",
         "Generated by `tools/registry/triage_exits.py` (coverage plan 1D, step 3). Re-run after a registry or config change.", "",
         f"Registry tokens: {len(toks)}. Without a pool or a loadable unwrap: {len(no_exit)}. Scan: {scan_note}.", "",
         "## By kind", "",
         "| kind | collateral somewhere | not collateral | next step |", "|---|---:|---:|---|"]
    for k in NEXT:
        L.append(f"| {k} | {rows[(k, True)]} | {rows[(k, False)]} | {NEXT[k]} |")
    L += ["", "Tokens that are not collateral anywhere need no exit: a liquidation never seizes them.", "",
          "## Seized without an exit (scan), by repaid USD", ""]
    if seized:
        L += ["| token | symbol | kind | liquidations | repaid USD |", "|---|---|---|---:|---:|"]
        for a, (n, usd) in sorted(seized.items(), key=lambda x: -x[1][1]):
            t = toks.get(a, {})
            k = kind_of(t, euler_shares, a) if t else "not in registry"
            L.append(f"| `{a}` | {t.get('symbol', '?')} | {k} | {n} | {usd:,.0f} |")
    else:
        L.append("- none in the scan" if SCAN.exists() else "- the scan has not been run")
    OUT.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"{OUT}: {len(no_exit)} tokens without an exit; {len(seized)} seized in the scan")


if __name__ == "__main__":
    main()
