[package]
name = "liq-state"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
liq-types = { path = "../liq-types" }
liq-protocol = { path = "../liq-protocol" }
alloy-primitives = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
criterion = { workspace = true }

[[bench]]
name = "store"
harness = false

[lints]
workspace = true
